In [1]:
# Artificial Neural Network

In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#importing the dataset
dataset = pd.read_csv("D:DS_TriS/Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
dataset.shape

(10000, 14)

In [5]:
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

In [6]:
X[0:5], y[0:5]

(array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
        [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
        [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
        [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
        [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]],
       dtype=object), array([1, 0, 1, 0, 0], dtype=int64))

In [7]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X[0:5]

C:\Users\Triple S\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Triple S\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
        4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
        4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, 0.0000000e+00,
        4.2000000e+01, 8.0000000e+00, 1.5966080e+05, 3.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 1.1393157e+05],
       [0.0000000e+00, 0.0000000e+00, 6.9900000e+02, 0.0000000e+00,
        3.9000000e+01, 1.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 9.3826630e+04],
       [0.0000000e+00, 1.0000000e+00, 8.5000000e+02, 0.0000000e+00,
        4.3000000e+01, 2.0000000e+00, 1.2551082e+05, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 7.9084100e+04]])

In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:

# Part 2 - Now let's make the ANN!



In [11]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [12]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\Users\Triple S\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """
C:\Users\Triple S\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
C:\Users\Triple S\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()


In [13]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\Users\Triple S\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 2s 217us/step - loss: 0.4877 - accuracy: 0.7956
Epoch 2/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.4287 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.4221 - accuracy: 0.7983
Epoch 4/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.4174 - accuracy: 0.8245
Epoch 5/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.4160 - accuracy: 0.8273
Epoch 6/100
8000/8000 [==============================] - 2s 190us/step - loss: 0.4138 - accuracy: 0.8296
Epoch 7/100
8000/8000 [==============================] - 2s 210us/step - loss: 0.4123 - accuracy: 0.8322
Epoch 8/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.4112 - accuracy: 0.8305
Epoch 9/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.4101 - accuracy: 0.8326
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 2s 284us/step - loss: 0.4003 - accuracy: 0.8340
Epoch 79/100
8000/8000 [==============================] - 3s 338us/step - loss: 0.4005 - accuracy: 0.8353
Epoch 80/100
8000/8000 [==============================] - 3s 376us/step - loss: 0.3999 - accuracy: 0.8353
Epoch 81/100
8000/8000 [==============================] - 3s 316us/step - loss: 0.4000 - accuracy: 0.8342
Epoch 82/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.4001 - accuracy: 0.8347
Epoch 83/100
8000/8000 [==============================] - 2s 256us/step - loss: 0.4003 - accuracy: 0.8336
Epoch 84/100
8000/8000 [==============================] - 2s 250us/step - loss: 0.4005 - accuracy: 0.8364
Epoch 85/100
8000/8000 [==============================] - 2s 279us/step - loss: 0.3999 - accuracy: 0.8353
Epoch 86/100
8000/8000 [==============================] - 3s 332us/step - loss: 0.4005 - accuracy: 0.8357
Epoch 87/100
8000/8000 [==============================] - 2

In [15]:

# Part 3 - Making the predictions and evaluating the model



In [16]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [17]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [18]:
cm

array([[1555,   40],
       [ 277,  128]], dtype=int64)

In [21]:
accuracy = (1555+128)/2000
accuracy

0.8415